#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1619864867

/*
 * Macros for device 'fifo_pls_out', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_PLS_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_PLS_OUT_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_PLS_OUT_COMPONENT_NAME fifo_pls
#define FIFO_PLS_OUT_BASE 0x1f000
#define FIFO_PLS_OUT_SPAN 8
#define FIFO_PLS_OUT_END 0x1f007
#define FIFO_PLS_OUT_AVALONMM_AVALONMM_DATA_WIDTH 64
#define FIFO_PLS_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_PLS_OUT_BITS_PER_SYMBOL 32
#define FIFO_PLS_OUT_CHANNEL_WIDTH 8
#define FIFO_PLS_OUT_ERROR_WIDTH 8
#define FIFO_PLS_OUT_FIFO_DEPTH 1024
#define FIFO_PLS_OUT_SINGLE_CLOCK_MODE 0
#define FIFO_PLS_OUT_SYMBOLS_PER_BEAT 1
#define FIFO_PLS_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_PLS_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_PLS_OUT_USE_AVALONST_SINK 0
#define FIFO_PLS_OUT_USE_AVALONST_SOURCE 0
#define FIFO_PLS_OUT_USE_BACKPRESSURE 0
#define FIFO_PLS_OUT_USE_IRQ 0
#define FIFO_PLS_OUT_USE_PACKET 0
#define FIFO_PLS_OUT_USE_READ_CONTROL 1
#define FIFO_PLS_OUT_USE_REGISTER 0
#define FIFO_PLS_OUT_USE_WRITE_CONTROL 1

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'fifo_pls_out_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_PLS_OUT_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_PLS_OUT_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_PLS_OUT_CSR_COMPONENT_NAME fifo_pls
#define FIFO_PLS_OUT_CSR_BASE 0x2f000
#define FIFO_PLS_OUT_CSR_SPAN 32
#define FIFO_PLS_OUT_CSR_END 0x2f01f
#define FIFO_PLS_OUT_CSR_AVALONMM_AVALONMM_DATA_WIDTH 64
#define FIFO_PLS_OUT_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_PLS_OUT_CSR_BITS_PER_SYMBOL 32
#define FIFO_PLS_OUT_CSR_CHANNEL_WIDTH 8
#define FIFO_PLS_OUT_CSR_ERROR_WIDTH 8
#define FIFO_PLS_OUT_CSR_FIFO_DEPTH 1024
#define FIFO_PLS_OUT_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_PLS_OUT_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_PLS_OUT_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_PLS_OUT_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_PLS_OUT_CSR_USE_AVALONST_SINK 0
#define FIFO_PLS_OUT_CSR_USE_AVALONST_SOURCE 0
#define FIFO_PLS_OUT_CSR_USE_BACKPRESSURE 0
#define FIFO_PLS_OUT_CSR_USE_IRQ 0
#define FIFO_PLS_OUT_CSR_USE_PACKET 0
#define FIFO_PLS_OUT_CSR_USE_READ_CONTROL 1
#define FIFO_PLS_OUT_CSR_USE_REGISTER 0
#define FIFO_PLS_OUT_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_pls_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_PLS_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_PLS_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_PLS_IN_CSR_COMPONENT_NAME fifo_pls
#define FIFO_PLS_IN_CSR_BASE 0x3f000
#define FIFO_PLS_IN_CSR_SPAN 32
#define FIFO_PLS_IN_CSR_END 0x3f01f
#define FIFO_PLS_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 64
#define FIFO_PLS_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_PLS_IN_CSR_BITS_PER_SYMBOL 32
#define FIFO_PLS_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_PLS_IN_CSR_ERROR_WIDTH 8
#define FIFO_PLS_IN_CSR_FIFO_DEPTH 1024
#define FIFO_PLS_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_PLS_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_PLS_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_PLS_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_PLS_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_PLS_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_PLS_IN_CSR_USE_BACKPRESSURE 0
#define FIFO_PLS_IN_CSR_USE_IRQ 0
#define FIFO_PLS_IN_CSR_USE_PACKET 0
#define FIFO_PLS_IN_CSR_USE_READ_CONTROL 1
#define FIFO_PLS_IN_CSR_USE_REGISTER 0
#define FIFO_PLS_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'Pulse_counter', class 'Pulse_counter'
 * The macros are prefixed with 'PULSE_COUNTER_'.
 * The prefix is the slave descriptor.
 */
#define PULSE_COUNTER_COMPONENT_TYPE Pulse_counter
#define PULSE_COUNTER_COMPONENT_NAME Pulse_counter
#define PULSE_COUNTER_BASE 0x4f000
#define PULSE_COUNTER_SPAN 4
#define PULSE_COUNTER_END 0x4f003

/*
 * Macros for device 'Trigger', class 'trigger_gen'
 * The macros are prefixed with 'TRIGGER_'.
 * The prefix is the slave descriptor.
 */
#define TRIGGER_COMPONENT_TYPE trigger_gen
#define TRIGGER_COMPONENT_NAME Trigger
#define TRIGGER_BASE 0x5f000
#define TRIGGER_SPAN 4
#define TRIGGER_END 0x5f003

/*
 * Macros for device 'trigger_sim', class 'trigger_gen'
 * The macros are prefixed with 'TRIGGER_SIM_'.
 * The prefix is the slave descriptor.
 */
#define TRIGGER_SIM_COMPONENT_TYPE trigger_gen
#define TRIGGER_SIM_COMPONENT_NAME trigger_sim
#define TRIGGER_SIM_BASE 0x6f000
#define TRIGGER_SIM_SPAN 4
#define TRIGGER_SIM_END 0x6f003


#endif /* _ALTERA_HPS_0_H_ */
